#spring:
#  application:
#    name: batch
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/batch-study
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: 12
#
#  batch:
#    jdbc:
#      initialize-schema: always

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      username: root
      password: whoareyou!12
    url: jdbc:mysql://127.0.0.1:3306/batchtest?useUnicode=true&characterEncoding=utf8&clusterInstanceHostPattern=?&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    # defer-datasource-initialization: true
  batch:
    job:
      name: STOP_STEP_TASK

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: study.batch.chapter.jobs.model,study.batch.practice.chapter8