spring:
  application:
    name: batch
  datasource:
    url: jdbc:h2:tcp://localhost/~/batch-study
    driver-class-name: org.h2.Driver
    username: sa
    password: 12

  batch:
    jdbc:
      initialize-schema: always